REFS : #44 and fixes #44 (completed day 15 task)
rx-training/Training-Jan-2021 pull request #176
Opened 2021-02-01 11:22 UTC by charmi-tanna

REFS : #44 and fixes #44 (completed day 15 task)

2021-02-02 11:28 UTC, MilitPanchasara commented on Modules/JavaScript/Day15/Charmi Tanna/Assignment/assignment1.html
> +            document.getElementById("myForm").reset();
Also reset content of result

2021-02-02 11:52 UTC, MilitPanchasara requested changes

2021-02-02 11:52 UTC, MilitPanchasara commented on Modules/JavaScript/Day16/Charmi Tanna/Assignment/assignment.html
> +
Leap year conditions are not working properly.

2021-02-03 08:33 UTC, radixdt12020 requested changes
as per discussion rework on assignment of day17

2021-02-11 11:52 UTC, merged