Trainee site done
rx-training/Training-Jan-2021 pull request #261
Opened 2021-03-03 05:47 UTC by jevikraiyani12

2021-03-04 08:53 UTC, jevikraiyani12 commented
REFS: #265 and fixes #120

2021-03-04 09:02 UTC, jevikraiyani12 commented
REFS #120 and fixes #120

2021-03-05 04:50 UTC, radixdt12020 requested changes
Add more fields in car sales business

2021-03-05 04:51 UTC, radixdt12020 commented on Modules/SQL/Day1/Practical-Assignment/SQLQuery1.sql
> +		AddressPerson varchar(30) chkAddressPerson C
incomplete

2021-03-05 04:51 UTC, radixdt12020 requested changes
Data type should be capital

2021-03-05 08:07 UTC, jevikraiyani12 commented
REFS:120 and fixes #120

2021-03-05 08:11 UTC, radixdt12020 commented on Modules/SQL/Day1/jevik-raiyani/Practical-Assignment/SQLQuery1.sql
> +	MinSalary INT CHECK (MinSalary> 8000) NOT NULL,
default value should be 8000 
this constraint is missing

2021-03-05 08:14 UTC, merged