Refs #120 and fixes (Sql Day1)
rx-training/Training-Jan-2021 pull request #283
Opened 2021-03-05 10:59 UTC by shekharx

2021-03-05 11:13 UTC, radixdt12020 commented on Modules/SQL/Day1/Shekhar chawla/day1.sql
> +CREATE TABLE countries(
C Should be capital

2021-03-05 11:17 UTC, radixdt12020 requested changes
make all these changes

2021-03-05 11:17 UTC, radixdt12020 commented on Modules/SQL/Day1/Shekhar chawla/day1.sql
> +CREATE TABLE countries(
string value should be single

2021-03-09 08:27 UTC, radixdt12020 requested changes
Convert All the Queries into MS Sql

2021-03-18 08:46 UTC, MilitPanchasara reviewed
Day3 => practice from videos not done. (like practice on COALESCE, EOMONTH, PARSE, TRY_PARSE & math functions)

2021-03-18 08:49 UTC, MilitPanchasara reviewed
Day4 => Video exercise not done. Practice on ROLLUP, CUBE etc

2021-03-24 07:29 UTC, merged