Day2 Work Done(Ankur Chovatiya)
rx-training/Training-Jan-2021 pull request #284
Opened 2021-03-05 11:13 UTC by Anks1856

2021-03-08 10:19 UTC, radixdt12020 commented on Modules/SQL/Day2/Ankur_Chovatiya/Update_Query/SQLQuery9.sql
> +UPDATE Employees
check condition for null

2021-03-08 10:22 UTC, radixdt12020 requested changes
please work on comments

2021-03-08 11:21 UTC, Anks1856 commented on Modules/SQL/Day2/Ankur_Chovatiya/Update_Query/SQLQuery9.sql
> +UPDATE Employees
Changes updated

2021-03-09 09:32 UTC, radixdt12020 approved these changes

2021-03-09 09:32 UTC, merged